FROM node:22-alpine

WORKDIR /app

ENV CI=true

# Copy package files
COPY package.json pnpm-lock.yaml* ./

# Install dependencies
RUN npm install -g pnpm
RUN pnpm install --ignore-scripts --no-frozen-lockfile

# Copy source
COPY . .

# Expose port
EXPOSE 3000

# Start dev server
CMD ["pnpm", "dev"]